[[main]]
  name = "Introduce"
  url = "/about"
  weight = 10

[[main]]
  name = "News"
  pageRef = "/categories/news/"
  weight = 20


[[main]]
  name = "Members"
  pageRef = "members"
  weight = 30

[[main]]
  name = "Publications"
  pageRef = "archive"
  weight = 40


[[main]]
  name = "Research Projects"
  weight = 50
  pageRef = "/categories/projects/"

